* Тестовое задание:
Необходимо предложить стратегию, в рамках которой подробно описать решение таких задач, как:

1. Получение нескольких ракурсов одного помещения с минимальным
 расхождением. Важно привязываться к расстановке мебели на плане.

2. Внесение правок детально (точечно, не меняя всего, только
 конкретные объекты или текстуру объекта)

Входные данные:
- 3д модели из Ревита или 3д макса,
- планировочные решения с расстановкой мебели,
- референсы в виде картинок интерьеров,
- фото предметов интерьера
- описания предметов интерьера,
- габариты объектов,
- скетчи,
- коллажи,
- серомодельные рендеры пространства (без мебели и текстур),
- финальные рендер смежных помещений, для генерации  текстур и формы по их подобию.
* термины
- ракурсы - angle (camera angle, perspective jellinek);  line of sight ; shooting angle
- interior design - дизайн интерера
* Выполнено
- осмотрелся на huggingface, настроил inference через api для себя на будущее к языковым моделям
- поговорил с ChatGPT, LLama2
- был проверен arxiv.org по темам: image-to-image, RotationNet, Rotation Invariance
- был использован scholar.google.com
* Набросок Стратегии
*Задача 1)* Коммерческие продукты, которые возможно могут делать поворот: Abode Photoshop transform, DeepArt.io, OpenAI CLIP.

Необходама нейронная сеть особого типа с 3д информацией об объектах, такие сети сложны и узко
 специализированы в биометрии, медицине и добывающей промышленности. (в свободном доступе
 модель я не нешел пока готовых решений)
- layers: 3D convolutional layers or volumetric convolution, Capule networks, RotationNet.
- rotation sensitive networks: PointNet++, IM-NET, Occupancy Net++ [fn:1]

Можно попробовать большие интеллектуальные мультимодальные модели с чательно подготовленным входными
 данными. Но с ними тяжело будет добиться минимальных расхождений, необходимо экспериментировать.

Можно объединить предобученную генеративную сеть image-to-image с RotationNet или/и 3D-PRNN.

Эта работа по конструированию и обучение сети займет примерно 4-7 месяцев. Как минимум месяц на
 планирование и подробное исследование перечисленных выше слоев и моделей сетей.

Так как в дизайне используются изображения высокого разрешения, то для конечного решения будут
 необходимы достаточные вычислительные мощности: GPU последнего поколения, как минимум.

*Задача 2)* Можно использовать Fine tuning на средних сверточных моделях для правок детально, например
 замена объекта.
- генерации сцены по детальной 3Д модели
- изменение отдельных частей изображения
- синтез двух изображений
- реконструкция или заполнение пустых частей

Эти задачи намного легче и потребуют 1-2 месяца или меньше.

* Footnotes

[fn:1] Evoluating 3D Shape Analysis Methods for Robustness to Rotation Invariance
